var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/posts/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__54c740ae._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/_36aaca9d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c0bc042._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e82ee19._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__ded06c13._.js")
R.c("server/chunks/ssr/lib_wordpress_api_ts_92db619a._.js")
R.c("server/chunks/ssr/app_error_tsx_5275429f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_posts_page_actions_af0e0c81.js")
R.m(7545)
module.exports=R.m(7545).exports
